# Generated by Django 3.1.7 on 2021-03-07 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("inventory", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="device", name="remarks", field=models.TextField(null=True)
        )
    ]
