# Generated by Django 3.1.7 on 2021-03-07 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("inventory", "0002_device_remarks")]

    operations = [
        migrations.AlterField(
            model_name="device", name="remarks", field=models.TextField(blank=True)
        )
    ]
